In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [26]:
data2020 = pd.read_csv('data/2020.csv')
data2021 = pd.read_csv('data/2021.csv')
data2022 = pd.read_csv('data/2022.csv')
data2023 = pd.read_csv('data/2023.csv')
data2024 = pd.read_csv('data/2024.csv')
data2025 = pd.read_csv('data/2025.csv')

# https://data.boston.gov/dataset/property-assessment
# https://data.boston.gov/organization/boston-maps
# https://www.gensler.com/gri/return-of-the-city (2021 - 2024)

/var/folders/wy/50c5sv7n4wsfhhww_wwjz2tr0000gn/T/ipykernel_5398/2205848421.py:1: DtypeWarning: Columns (6,15,27,28,29,34,35,36,37,38,39,40,41,42,44,45,46,47,48,58,59,64,65,66,67,68,69,70,72,73,74) have mixed types. Specify dtype option on import or set low_memory=False.
  data2020 = pd.read_csv('data/2020.csv')
/var/folders/wy/50c5sv7n4wsfhhww_wwjz2tr0000gn/T/ipykernel_5398/2205848421.py:5: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  data2024 = pd.read_csv('data/2024.csv')
/var/folders/wy/50c5sv7n4wsfhhww_wwjz2tr0000gn/T/ipykernel_5398/2205848421.py:6: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  data2025 = pd.read_csv('data/2025.csv')

In [27]:
data2020.head()

,PID,CM_ID,GIS_ID,ST_NUM,ST_NAME,ST_NAME_SUF,UNIT_NUM,ZIPCODE,PTYPE,LU,...,U_BTH_STYLE2,U_BTH_STYLE3,U_KITCH_TYPE,U_KITCH_STYLE,U_HEAT_TYP,U_AC,U_FPLACE,U_INT_FIN,U_INT_CND,U_VIEW
0,100271002,100271000.0,100271000,356,PRINCETON,ST,1,2128.0,102,CD,...,NaN,NaN,F - Full Eat In,M - Modern,W - Ht Water/Steam,N - None,0.0,N - Normal,G - Good,A - Average
1,100271004,100271000.0,100271000,356,PRINCETON,ST,2,2128.0,102,CD,...,NaN,NaN,F - Full Eat In,M - Modern,W - Ht Water/Steam,N - None,0.0,N - Normal,G - Good,A - Average
2,100271006,100271000.0,100271000,356,PRINCETON,ST,3,2128.0,102,CD,...,NaN,NaN,F - Full Eat In,M - Modern,W - Ht Water/Steam,N - None,0.0,N - Normal,G - Good,A - Average
3,100272000,NaN,100272000,352,PRINCETON,ST,NaN,2128.0,105,R3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100273000,NaN,100273000,,PRINCETON,ST,NaN,2128.0,132,RL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
data2021.head()

,PID,CM_ID,GIS_ID,ST_NUM,ST_NAME,UNIT_NUM,CITY,ZIPCODE,BLDG_SEQ,NUM_BLDGS,...,KITCHEN_STYLE2,KITCHEN_STYLE3,HEAT_TYPE,HEAT_FUEL,AC_TYPE,FIRE_PLACE,PlUMBING,NUM_PARKING,PROP_VIEW,CORNER_UNIT
0,100001000,NaN,100001000.0,104 A 104,PUTNAM ST,NaN,EAST BOSTON,2128,1.0,1.0,...,S - Semi-Modern,S - Semi-Modern,W - Ht Water/Steam,NaN,N - None,NaN,NaN,3.0,A - Average,NaN
1,100002000,NaN,100002000.0,197,LEXINGTON ST,NaN,EAST BOSTON,2128,1.0,1.0,...,M - Modern,M - Modern,F - Forced Hot Air,NaN,C - Central AC,NaN,NaN,NaN,A - Average,NaN
2,100003000,NaN,100003000.0,199,LEXINGTON ST,NaN,EAST BOSTON,2128,1.0,1.0,...,S - Semi-Modern,S - Semi-Modern,S - Space Heat,NaN,N - None,NaN,NaN,NaN,A - Average,NaN
3,100004000,NaN,100004000.0,201,LEXINGTON ST,NaN,EAST BOSTON,2128,1.0,1.0,...,S - Semi-Modern,S - Semi-Modern,W - Ht Water/Steam,NaN,N - None,NaN,NaN,NaN,A - Average,NaN
4,100005000,NaN,100005000.0,203,LEXINGTON ST,NaN,EAST BOSTON,2128,1.0,1.0,...,S - Semi-Modern,NaN,W - Ht Water/Steam,NaN,N - None,NaN,NaN,NaN,A - Average,NaN

In [30]:
data2020.columns

Index(['PID', 'CM_ID', 'GIS_ID', 'ST_NUM', 'ST_NAME', 'ST_NAME_SUF',
       'UNIT_NUM', 'ZIPCODE', 'PTYPE', 'LU', 'OWN_OCC', 'OWNER',
       'MAIL_ADDRESSEE', 'MAIL_ADDRESS', 'MAIL CS', 'MAIL_ZIPCODE', 'AV_LAND',
       'AV_BLDG', 'AV_TOTAL', 'GROSS_TAX', 'LAND_SF', 'YR_BUILT', 'YR_REMOD',
       'GROSS_AREA', 'LIVING_AREA', 'NUM_FLOORS', 'STRUCTURE_CLASS',
       'R_BLDG_STYL', 'R_ROOF_TYP', 'R_EXT_FIN', 'R_TOTAL_RMS', 'R_BDRMS',
       'R_FULL_BTH', 'R_HALF_BTH', 'R_BTH_STYLE', 'R_BTH_STYLE2',
       'R_BTH_STYLE3', 'R_KITCH', 'R_KITCH_STYLE', 'R_KITCH_STYLE2',
       'R_KITCH_STYLE3', 'R_HEAT_TYP', 'R_AC', 'R_FPLACE', 'R_EXT_CND',
       'R_OVRALL_CND', 'R_INT_CND', 'R_INT_FIN', 'R_VIEW', 'S_NUM_BLDG',
       'S_BLDG_STYL', 'S_UNIT_RES', 'S_UNIT_COM', 'S_UNIT_RC', 'S_EXT_FIN',
       'S_EXT_CND', 'U_BASE_FLOOR', 'U_NUM_PARK', 'U_CORNER', 'U_ORIENT',
       'U_TOT_RMS', 'U_BDRMS', 'U_FULL_BTH', 'U_HALF_BTH', 'U_BTH_STYLE',
       'U_BTH_STYLE2', 'U_BTH_STYLE3', 'U_KITCH_TYPE', 'U_KITCH_STYLE',
       'U_HEAT_TYP', 'U_AC', 'U_FPLACE', 'U_INT_FIN', 'U_INT_CND', 'U_VIEW'],
      dtype='object')

In [ ]:
# Check if there is any change in pid
# change pid to ing
data2020['PID'] = data2020['PID'].astype(int)
data2021['PID'] = data2021['PID'].astype(int)
data2022['PID'] = data2022['PID'].astype(int)
data2023['PID'] = data2023['PID'].astype(int)
data2024['PID'] = data2024['PID'].astype(int)

print(data2020['PID'].nunique())
print(data2021['PID'].nunique())
print(data2022['PID'].nunique())
print(data2023['PID'].nunique())
print(data2024['PID'].nunique())

174714
176915
178422
180448
182235

In [35]:
# we will first tackle 2020
# Check if there are any empty GIS_ID
print(data2020[data2020['GIS_ID'].isna()])

# check if any of them are not digits
# change to string temporarily
data2020['GIS_ID'] = data2020['GIS_ID'].astype(str)
print(data2020[~data2020['GIS_ID'].str.isdigit()])

# change back to int
data2020['GIS_ID'] = data2020['GIS_ID'].astype(int)

Empty DataFrame
Columns: [PID, CM_ID, GIS_ID, ST_NUM, ST_NAME, ST_NAME_SUF, UNIT_NUM, ZIPCODE, PTYPE, LU, OWN_OCC, OWNER, MAIL_ADDRESSEE, MAIL_ADDRESS, MAIL CS, MAIL_ZIPCODE, AV_LAND, AV_BLDG, AV_TOTAL, GROSS_TAX, LAND_SF, YR_BUILT, YR_REMOD, GROSS_AREA, LIVING_AREA, NUM_FLOORS, STRUCTURE_CLASS, R_BLDG_STYL, R_ROOF_TYP, R_EXT_FIN, R_TOTAL_RMS, R_BDRMS, R_FULL_BTH, R_HALF_BTH, R_BTH_STYLE, R_BTH_STYLE2, R_BTH_STYLE3, R_KITCH, R_KITCH_STYLE, R_KITCH_STYLE2, R_KITCH_STYLE3, R_HEAT_TYP, R_AC, R_FPLACE, R_EXT_CND, R_OVRALL_CND, R_INT_CND, R_INT_FIN, R_VIEW, S_NUM_BLDG, S_BLDG_STYL, S_UNIT_RES, S_UNIT_COM, S_UNIT_RC, S_EXT_FIN, S_EXT_CND, U_BASE_FLOOR, U_NUM_PARK, U_CORNER, U_ORIENT, U_TOT_RMS, U_BDRMS, U_FULL_BTH, U_HALF_BTH, U_BTH_STYLE, U_BTH_STYLE2, U_BTH_STYLE3, U_KITCH_TYPE, U_KITCH_STYLE, U_HEAT_TYP, U_AC, U_FPLACE, U_INT_FIN, U_INT_CND, U_VIEW]
Index: []

[0 rows x 75 columns]
Empty DataFrame
Columns: [PID, CM_ID, GIS_ID, ST_NUM, ST_NAME, ST_NAME_SUF, UNIT_NUM, ZIPCODE, PTYPE, LU, OWN_OCC, OWNER, MAIL_ADDRESSEE, MAIL_ADDRESS, MAIL CS, MAIL_ZIPCODE, AV_LAND, AV_BLDG, AV_TOTAL, GROSS_TAX, LAND_SF, YR_BUILT, YR_REMOD, GROSS_AREA, LIVING_AREA, NUM_FLOORS, STRUCTURE_CLASS, R_BLDG_STYL, R_ROOF_TYP, R_EXT_FIN, R_TOTAL_RMS, R_BDRMS, R_FULL_BTH, R_HALF_BTH, R_BTH_STYLE, R_BTH_STYLE2, R_BTH_STYLE3, R_KITCH, R_KITCH_STYLE, R_KITCH_STYLE2, R_KITCH_STYLE3, R_HEAT_TYP, R_AC, R_FPLACE, R_EXT_CND, R_OVRALL_CND, R_INT_CND, R_INT_FIN, R_VIEW, S_NUM_BLDG, S_BLDG_STYL, S_UNIT_RES, S_UNIT_COM, S_UNIT_RC, S_EXT_FIN, S_EXT_CND, U_BASE_FLOOR, U_NUM_PARK, U_CORNER, U_ORIENT, U_TOT_RMS, U_BDRMS, U_FULL_BTH, U_HALF_BTH, U_BTH_STYLE, U_BTH_STYLE2, U_BTH_STYLE3, U_KITCH_TYPE, U_KITCH_STYLE, U_HEAT_TYP, U_AC, U_FPLACE, U_INT_FIN, U_INT_CND, U_VIEW]
Index: []

[0 rows x 75 columns]

In [36]:
# now for tackling 2024
# Check if there are any empty GIS_ID
print(data2024[data2024['GIS_ID'].isna()])

# check if any of them are not digits
# change to string temporarily
data2024['GIS_ID'] = data2024['GIS_ID'].astype(str)
print(data2024[~data2024['GIS_ID'].str.isdigit()])

# change back to int
data2024['GIS_ID'] = data2024['GIS_ID'].astype(int)

Empty DataFrame
Columns: [PID, CM_ID, GIS_ID, ST_NUM, ST_NAME, UNIT_NUM, CITY, ZIP_CODE, BLDG_SEQ, NUM_BLDGS, LUC, LU, LU_DESC, BLDG_TYPE, OWN_OCC, OWNER, MAIL_ADDRESSEE, MAIL_STREET_ADDRESS, MAIL_CITY, MAIL_STATE, MAIL_ZIP_CODE, RES_FLOOR, CD_FLOOR, RES_UNITS, COM_UNITS, RC_UNITS, LAND_SF, GROSS_AREA, LIVING_AREA, LAND_VALUE, BLDG_VALUE, SFYI_VALUE, TOTAL_VALUE,  GROSS_TAX , YR_BUILT, YR_REMODEL, STRUCTURE_CLASS, ROOF_STRUCTURE, ROOF_COVER, INT_WALL, EXT_FNISHED, INT_COND, EXT_COND, OVERALL_COND, BED_RMS, FULL_BTH, HLF_BTH, KITCHENS, TT_RMS, BDRM_COND, BTHRM_STYLE1, BTHRM_STYLE2, BTHRM_STYLE3, KITCHEN_TYPE, KITCHEN_STYLE1, KITCHEN_STYLE2, KITCHEN_STYLE3, HEAT_TYPE, HEAT_SYSTEM, AC_TYPE, FIREPLACES, ORIENTATION, NUM_PARKING, PROP_VIEW, CORNER_UNIT]
Index: []

[0 rows x 65 columns]
Empty DataFrame
Columns: [PID, CM_ID, GIS_ID, ST_NUM, ST_NAME, UNIT_NUM, CITY, ZIP_CODE, BLDG_SEQ, NUM_BLDGS, LUC, LU, LU_DESC, BLDG_TYPE, OWN_OCC, OWNER, MAIL_ADDRESSEE, MAIL_STREET_ADDRESS, MAIL_CITY, MAIL_STATE, MAIL_ZIP_CODE, RES_FLOOR, CD_FLOOR, RES_UNITS, COM_UNITS, RC_UNITS, LAND_SF, GROSS_AREA, LIVING_AREA, LAND_VALUE, BLDG_VALUE, SFYI_VALUE, TOTAL_VALUE,  GROSS_TAX , YR_BUILT, YR_REMODEL, STRUCTURE_CLASS, ROOF_STRUCTURE, ROOF_COVER, INT_WALL, EXT_FNISHED, INT_COND, EXT_COND, OVERALL_COND, BED_RMS, FULL_BTH, HLF_BTH, KITCHENS, TT_RMS, BDRM_COND, BTHRM_STYLE1, BTHRM_STYLE2, BTHRM_STYLE3, KITCHEN_TYPE, KITCHEN_STYLE1, KITCHEN_STYLE2, KITCHEN_STYLE3, HEAT_TYPE, HEAT_SYSTEM, AC_TYPE, FIREPLACES, ORIENTATION, NUM_PARKING, PROP_VIEW, CORNER_UNIT]
Index: []

[0 rows x 65 columns]

In [ ]:
# check any intersecting pids between 2020 and 2024

key = "GIS_ID"

set2020 = set(data2020[key])
# set2021 = set(data2021[key])
# set2022 = set(data2022[key])
# set2023 = set(data2023[key])
set2024 = set(data2024[key])
# set2025 = set(data2025[key])


# find the intersecting 

# print the intersecting pids
print('hi')

intersecting_pids = set2020 & set2024
print(len(intersecting_pids))   

# list the intersecting pids
# print(list(intersecting_pids))
# set1 = set([1, 2, 3])
# set2 = set([2, 3, 4])
# intersection = set1 & set2
# print(intersection)

# create a csv just with GIS_ID column

gis_pd = pd.DataFrame({'GIS_ID_INTERSECT': list(intersecting_pids)})
gis_pd.to_csv('gis_id.csv', index=False)

#

hi
98283

In [4]:
# dataset for 2021
# https://gis.bostonplans.org/hosting/rest/services/Parcels_21_detailed/MapServer/0

# dataset for 2024 
# https://gis.bostonplans.org/hosting/rest/services/Parcels_24_detailed/FeatureServer

# tourism, restaurant, landmark
# https://www.arcgis.com/home/item.html?id=b0a5c64fb821488db96282c39ff1d843
# https://services2.arcgis.com/I9cUOJUZvdGAJncI/arcgis/rest/services/Boston_Tourism_Attractions___Theo_Sox__Spring_2024/FeatureServer

# Boston music venues
# https://www.arcgis.com/home/item.html?id=2218ae9effb04da8bac96c21987bec3c
# https://services1.arcgis.com/qN3V93cYGMKQCOxL/arcgis/rest/services/p2_music_venues__East_Mass__WFL1/FeatureServer

# Boston farmer market
# https://harvard-cga.maps.arcgis.com/home/item.html?id=bc0d3b15350d4dd4adcb908109d4923d
# https://services2.arcgis.com/I9cUOJUZvdGAJncI/arcgis/rest/services/Boston_Farmers_Markets/FeatureServer

# Boston park
# https://harvard-cga.maps.arcgis.com/home/item.html?id=226482699b3a425fa6f2f8c67295b1da

# Boston noise incidents
# https://www.arcgis.com/home/item.html?id=4d48d718f3134dddb9b8bba0a768d4cd

# Boston crime rates
# https://www.arcgis.com/home/item.html?id=f22dcdba5f3d424b9ea0ee31c59967b5

# Level of traffic
# https://www.arcgis.com/home/item.html?id=7feb17ccdc324bc38f402630e7df3c06

# Boston public libraries
# https://boston.maps.arcgis.com/home/item.html?id=cb00f9248aa6404ab741071ca3806c0e

# Inflation rate
# https://www.macrotrends.net/global-metrics/countries/USA/united-states/inflation-rate-cpi#:~:text=Inflation%20as%20measured%20by%20the,a%200.58%25%20decline%20from%202019.

# Boston healthcare
# https://www.arcgis.com/home/item.html?id=fd726cf72b4d4ce3a599db1036d2ec7e

# Boston Police Department
# https://www.arcgis.com/home/item.html?id=e5a0066d38ac4e2abbc7918197a4f6af

# Boston Public School Assets
# https://www.arcgis.com/home/item.html?id=2690b82057424274a52648699895fb14

# Boston Universities
# https://www.arcgis.com/home/item.html?id=359e813a709b4d708a7cdb022c9bf4e4

# Boston Fire Department
# https://boston.maps.arcgis.com/home/item.html?id=092857c15cbb49e8b214ca5e228317a1

# Boston Sports
# https://gis.data.mass.gov/datasets/CambridgeGIS::sports-areas/about

# Boston street trees
# https://bostonopendata-boston.opendata.arcgis.com/maps/boston::treekeeper-street-trees

# Boston bus stops
# https://www.arcgis.com/home/item.html?id=7ae31a78d54349c5b5ac8457d89419b0

# Boston movie theaters
# https://services1.arcgis.com/qN3V93cYGMKQCOxL/arcgis/rest/services/irl577_Harvard_CGA_MovieTheaters_v3_Layers/FeatureServer

# Boston sports stadiums

# Boston museum and art galleries
# https://www-tlstest.arcgis.com/home/item.html?id=9d1b74d024534c6cb484abb83525aef5